"""Model / system card generator (Markdown)."""
from __future__ import annotations

import sqlite3
from typing import Any

from .models import get_system, list_risks, risk_score


def system_card(conn: sqlite3.Connection, system_id: str) -> str:
    system = get_system(conn, system_id)
    if not system:
        raise ValueError("unknown system")

    risks = [r for r in list_risks(conn) if r["system_id"] == system_id]

    lines = [
        f"# AI System Card: {system['name']}",
        "",
        f"- **Owner:** {system['owner'] or 'unassigned'}",
        f"- **Type:** {system['system_type'] or 'unspecified'}",
        f"- **Risk level:** {system['risk_level']}",
        f"- **Status:** {system['status']}",
        "",
        "## Description",
        "",
        system["description"] or "_No description provided._",
        "",
        "## Intended Use",
        "",
        "_Document the intended purpose and users of this system._",
        "",
        "## Risk Assessment",
        "",
    ]
    if not risks:
        lines.append("_No risks registered._")
    else:
        lines.append("| Risk | Category | Score (LxI) | Status | Mitigation |")
        lines.append("|---|---|---|---|---|")
        for r in risks:
            lines.append(
                f"| {r['title']} | {r['category'] or '-'} | {risk_score(r)} | "
                f"{r['status']} | {r['mitigation'] or '-'} |"
            )

    lines += [
        "",
        "## Governance",
        "",
        "- [ ] Human oversight defined",
        "- [ ] Data governance documented",
        "- [ ] Logging & monitoring enabled",
        "- [ ] Incident reporting process in place",
        "",
        "_Generated by ai-compliance-hub._",
    ]
    return "\n".join(lines)


def model_card(model: dict[str, Any]) -> str:
    """A standalone model card from a metadata dict."""
    return "\n".join(
        [
            f"# Model Card: {model.get('name', 'unnamed')}",
            "",
            f"- **Version:** {model.get('version', 'n/a')}",
            f"- **Owner:** {model.get('owner', 'unassigned')}",
            f"- **License:** {model.get('license', 'unspecified')}",
            "",
            "## Intended Use",
            "",
            model.get("intended_use", "_TBD_"),
            "",
            "## Training Data",
            "",
            model.get("training_data", "_TBD_"),
            "",
            "## Limitations & Risks",
            "",
            model.get("limitations", "_TBD_"),
            "",
            "## Evaluation",
            "",
            model.get("evaluation", "_TBD_"),
            "",
            "_Generated by ai-compliance-hub._",
        ]
    )
