header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: open-security-platform Authors
    content: |
      Copyright 2026 open-security-platform Authors.
      SPDX-License-Identifier: Apache-2.0
  paths:
    - '**/*.go'
  paths-ignore:
    - '**/node_modules/**'
    - 'identity/oiaf/**'
