#!/usr/bin/env bash
# Generate live/.env with strong random LOCAL-ONLY credentials from
# .env.example. Refuses to overwrite an existing .env unless FORCE=1.
# The values never leave this machine and must never be committed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIVE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$LIVE_DIR/.env"

if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
  echo "live/.env already exists — keeping it (FORCE=1 to regenerate)." >&2
  exit 0
fi

command -v openssl >/dev/null 2>&1 || { echo "openssl is required" >&2; exit 1; }

rand_hex() { openssl rand -hex "$1"; }

# Wazuh REST API password policy: 8-64 chars with upper, lower, digit, symbol.
# Charset stays bash/compose-source-safe (no $ ` " ' \ or spaces).
# The values below are consumed by the `cat > "$ENV_FILE"` heredoc at the end
# of this script; shellcheck does not count heredoc interpolation as a use.
# shellcheck disable=SC2034
WAZUH_API_PASSWORD="Wzp!9$(rand_hex 8)"
# shellcheck disable=SC2034
DD_ADMIN_PASSWORD="$(rand_hex 16)"
# shellcheck disable=SC2034
DD_DATABASE_PASSWORD="$(rand_hex 16)"
# shellcheck disable=SC2034
KEYCLOAK_ADMIN_PASSWORD="$(rand_hex 16)"
# shellcheck disable=SC2034
DD_SECRET_KEY="$(rand_hex 32)"
DD_CREDENTIAL_AES_256_KEY="$(rand_hex 16)" # exactly 32 chars
# shellcheck disable=SC2034
BAO_ROOT_TOKEN="osp-…ex 8)"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by live/scripts/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# LOCAL DOCKER PROOF STACK ONLY — never commit real values (live/.gitignore
# excludes this file). See live/.env.example for what each variable means.

KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
KEYCLOAK_REALM=osp

# Indexer credentials must match the bcrypt hash in the pinned upstream
# internal_users.yml (admin/SecretPassword) — do not randomize.
WAZUH_INDEXER_USER=admin
WAZUH_INDEXER_PASSWORD=SecretPassword
WAZUH_API_USER=wazuh-wui
WAZUH_API_PASSWORD=$WAZUH_API_PASSWORD

DD_ADMIN_USER=admin
DD_ADMIN_PASSWORD=$DD_ADMIN_PASSWORD
DD_DATABASE_USER=defectdojo
DD_DATABASE_PASSWORD=$DD_DATABASE_PASSWORD
DD_SECRET_KEY=$DD_SECRET_KEY
DD_CREDENTIAL_AES_256_KEY=$DD_CREDENTIAL_AES_256_KEY

BAO_ROOT_TOKEN=$BAO_ROOT_TOKEN

OLLAMA_MODEL=smollm2:135m
EOF

echo "Wrote $ENV_FILE (mode 600, random local-only credentials)."
